import 'package:pingo/constants/design_emojis.dart';
import 'package:pingo/constants/keyword_image.dart';
import 'package:pingo/constants/keywords.dart';

class Keyword {
  final String title;
  final String emoji;
  final String image;
  final int id;

  Keyword(this.title, this.id, this.emoji, this.image);
}

final allKeywords = placesKeywords + foods + musics + miscellaneous + other;

final placesKeywords = <Keyword>[
  Keyword(
    'Restaurant',
    Keywords.restaurant,
    DesignEmojis.restaurant,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Pub',
    Keywords.pub,
    DesignEmojis.pub,
    KeywordImage.pub,
  ),
  Keyword(
    'Party',
    Keywords.party,
    DesignEmojis.party,
    KeywordImage.party,
  ),
  Keyword(
    'Concert',
    Keywords.concert,
    DesignEmojis.concert,
    KeywordImage.concert,
  ),
  Keyword(
    'Children',
    Keywords.children,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Pets',
    Keywords.pet,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Park',
    Keywords.park,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Museum',
    Keywords.museum,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Store',
    Keywords.store,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Square',
    Keywords.square,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Historical',
    Keywords.historical,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Theater',
    Keywords.theater,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Bookstore',
    Keywords.bookstore,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Exposition',
    Keywords.exposition,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
];

final foods = <Keyword>[
  Keyword(
    'Brazilian',
    Keywords.brazilian,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Fast Food',
    Keywords.fastFood,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Pizza',
    Keywords.pizza,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Burger',
    Keywords.burger,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Hot Dog',
    Keywords.hotDog,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Candy',
    Keywords.candy,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Donuts',
    Keywords.donuts,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Japanese',
    Keywords.japanese,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Mexican',
    Keywords.mexican,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Chinese',
    Keywords.chinese,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Italian',
    Keywords.italian,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword('Thai', Keywords.thai, DesignEmojis.fastFood, KeywordImage.party),
  Keyword(
    'Greek',
    Keywords.greek,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Arabian',
    Keywords.arabian,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Coxinha',
    Keywords.coxinha,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Marmita',
    Keywords.marmita,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Pastel',
    Keywords.pastel,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Esfiha',
    Keywords.esfiha,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
];

final musics = <Keyword>[
  Keyword(
    'Rock',
    Keywords.rock,
    DesignEmojis.fastFood,
    KeywordImage.party,
  ),
  Keyword(
    'Pop',
    Keywords.pop,
    DesignEmojis.fastFood,
    KeywordImage.party,
  ),
  Keyword(
    'Country',
    Keywords.country,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Eletronic',
    Keywords.electronic,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword('Funk', Keywords.funk, DesignEmojis.fastFood, KeywordImage.party),
  Keyword(
    'House',
    Keywords.house,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword('Trap', Keywords.trap, DesignEmojis.fastFood, KeywordImage.party),
  Keyword(
    'Techno',
    Keywords.techno,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword('Rap', Keywords.rap, DesignEmojis.fastFood, KeywordImage.party),
  Keyword(
    'Samba',
    Keywords.samba,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Metal',
    Keywords.metal,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Pagode',
    Keywords.pagode,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Gospel',
    Keywords.gospel,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Classic',
    Keywords.classic,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword('MPB', Keywords.mpb, DesignEmojis.fastFood, KeywordImage.party),
  Keyword(
    'Blues',
    Keywords.blues,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword('Jazz', Keywords.jazz, DesignEmojis.fastFood, KeywordImage.party),
  Keyword(
    'Trance',
    Keywords.trance,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Hardcore',
    Keywords.hardcore,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword('Punk', Keywords.punk, DesignEmojis.fastFood, KeywordImage.party),
];

final miscellaneous = <Keyword>[
  Keyword('LGBT', Keywords.lgbt, DesignEmojis.fastFood, KeywordImage.party),
  Keyword(
    'Fashion',
    Keywords.fashion,
    DesignEmojis.shopping,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Gym',
    Keywords.gym,
    DesignEmojis.fastFood,
    KeywordImage.party,
  ),
  Keyword(
    'Beer',
    Keywords.beer,
    DesignEmojis.fastFood,
    KeywordImage.party,
  ),
  Keyword(
    'Sports',
    Keywords.sports,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Games',
    Keywords.games,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Dance',
    Keywords.dance,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Anime',
    Keywords.anime,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Chocolate',
    Keywords.chocolate,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Street Art',
    Keywords.streetArt,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Bike',
    Keywords.bike,
    DesignEmojis.fastFood,
    KeywordImage.party,
  ),
  Keyword(
    'Skate',
    Keywords.skate,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Rollerblades',
    Keywords.rollerblades,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword('Art', Keywords.art, DesignEmojis.fastFood, KeywordImage.party),
  Keyword(
    'Tattoo',
    Keywords.tattoo,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Meditation',
    Keywords.meditation,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Soccer',
    Keywords.soccer,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Basketball',
    Keywords.basketball,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Volleyball',
    Keywords.volleyball,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Tennis',
    Keywords.tennis,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword('UFC', Keywords.ufc, DesignEmojis.fastFood, KeywordImage.party),
  Keyword(
    'Boxing',
    Keywords.boxing,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Brazilian Jiu Jitsu',
    Keywords.bjj,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword(
    'Thai Boxing',
    Keywords.thaiBoxing,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
  Keyword('Gin', Keywords.gin, DesignEmojis.fastFood, KeywordImage.party),
  Keyword(
    'Drinks',
    Keywords.drinks,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
];

final other = [
  Keyword(
    'Event',
    Keywords.event,
    DesignEmojis.eventWoman,
    KeywordImage.party,
  ),
  Keyword(
    'Product',
    Keywords.product,
    DesignEmojis.product,
    KeywordImage.restaurant,
  ),
  Keyword('Util', Keywords.util, DesignEmojis.utils, KeywordImage.party),
  Keyword('Free', Keywords.free, DesignEmojis.fastFood, KeywordImage.party),
  Keyword('Open', Keywords.open, DesignEmojis.fastFood, KeywordImage.party),
  Keyword(
    'Promo',
    Keywords.promo,
    DesignEmojis.fastFood,
    KeywordImage.restaurant,
  ),
];
